# Setting up the Path
set -e fish_user_paths

## ADD to PATH ##
if test (uname) = "Darwin"
    # Homebrew generated by `brew shellenv`
    set -gx HOMEBREW_PREFIX /opt/homebrew
    set -gx HOMEBREW_CELLAR /opt/homebrew/Cellar
    set -gx HOMEBREW_REPOSITORY /opt/homebrew
    set -q PATH; or set PATH ''
    set -gx PATH /opt/homebrew/bin /opt/homebrew/sbin $PATH
    set -q MANPATH; or set MANPATH ''
    set -gx MANPATH /opt/homebrew/share/man $MANPATH
    set -q INFOPATH; or set INFOPATH ''
    set -gx INFOPATH /opt/homebrew/share/info $INFOPATH

    #set -U fish_user_paths "/usr/local/sbin" $fish_user_paths # homebrew - Intel
    set -g fish_user_paths $HOMEBREW_PREFIX/bin $fish_user_paths # homebrew ARM

    # openssl to path
    set -g fish_user_paths "/opt/homebrew/opt/openssl@1.1/bin" $fish_user_paths

    # Homebrew make - gmake - MacOS ships with v3.81
    set -g fish_user_paths /opt/homebrew/opt/make/libexec/gnubin $fish_user_paths
end

# asdf
source ~/.asdf/asdf.fish
set -g fish_user_paths $GOBIN $fish_user_paths

# Bun
set -gx BUN_INSTALL "$HOME/.bun"
set -g fish_user_paths $BUN_INSTALL $fish_user_paths

# Local scripts
set -g fish_user_paths $HOME/.local/bin $fish_user_paths

# FZF and FD helpers for NeoVim
set -x FZF_DEFAULT_COMMAND "fd --type f"
set -x FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"

# # Docker
# set -g fish_user_paths $HOME/.docker/bin $fish_user_paths